// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fsprahwgnccdvapivxby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzcHJhaHdnbmNjZHZhcGl2eGJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MzI4MjEsImV4cCI6MjA3MzQwODgyMX0._cpa3e0jUYKL_qxEjkaP6VnSRF9JynwyphnbBPWuQ9w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});